services:
  app:
    build: .
    container_name: flight_app
    ports:
      - "8010:80"
    volumes:
      - ./source:/var/www/html
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8
    container_name: flight_mysql
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: gestion_rh
        # Supprimez MYSQL_USER et MYSQL_PASSWORD ou utilisez un autre nom d'utilisateur
        MYSQL_USER: gestion_user
        MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  mysql_data:
