CREATE TABLE annonce_emploi(
   id SERIAL PRIMARY KEY,
   titre VARCHAR(200),
   description TEXT,
   competences_requises TEXT,
   diplomes_requis TEXT,
   experience_min INT,
   niveau_responsabilite VARCHAR(100),
   autonomie_requise TEXT,
   date_publication DATE,
   date_limite DATE,
   statut VARCHAR(50),
   id_poste BIGINT UNSIGNED,
   id_type_contrat BIGINT UNSIGNED,
   id_manager BIGINT UNSIGNED,
   FOREIGN KEY(id_poste) REFERENCES Poste(id),
   FOREIGN KEY(id_type_contrat) REFERENCES Type_Contrat(id),
   FOREIGN KEY(id_manager) REFERENCES Employe(id)
);
    CREATE TABLE candidature(
   id SERIAL PRIMARY KEY,
   nom VARCHAR(100),
   prenom VARCHAR(100),
   email VARCHAR(100),
   telephone VARCHAR(50),
   date_naissance DATE,
   adresse VARCHAR(255),
   cv_path VARCHAR(255),
   lettre_motivation_path VARCHAR(255),
   diplomes_path VARCHAR(255),
   experience_annees INT,
   note_manager DECIMAL(4,2),
   note_rh DECIMAL(4,2),
   score_final DECIMAL(4,2),
   statut VARCHAR(50),
   date_candidature DATE,
   date_entretien DATETIME,
   accepte_essai TINYINT(1),
   id_annonce BIGINT UNSIGNED,
   FOREIGN KEY(id_annonce) REFERENCES annonce_emploi(id)
);